version: '3.8'
services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    ports:
      - "1984:1984" # Mapea el puerto 1984 del host al contenedor
    volumes:
      # Monta el archivo de configuración desde el host al contenedor
      - C:/Users/zcami/Desktop/grafana-livecamera-rtsp-webrtc-main/go2rtc-config/go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped # Reinicia el contenedor automáticamente en caso de fallo


  grafana:
    build: './grafana'
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana/data
    ports:
      - "3000:3000" 
volumes:
  grafana_data: {}
 
